---
title: "2353_project"
author: "Ivy Zhao"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
bike <- read.csv("~/Downloads/bike+sharing+dataset/day.csv")
bikeDf<- subset(bike, select = c("yr", "season", "holiday", "workingday","weathersit", "temp", "atemp","hum", "windspeed", "cnt"))
summary(bikeDf)
nrow(bikeDf)
```


```{r}
#SD for continuous variables
sd_values <- sapply(bikeDf[, c("cnt", "temp", "atemp", "hum", "windspeed")], sd)
print(sd_values)
```

#Univariate Analysis on Categorical Data
```{r}
yr_counts <- table(bikeDf$yr) 
yr_percentages <- prop.table(yr_counts) * 100
yr_summary <- data.frame(yr = names(yr_counts),
                             Count = as.numeric(yr_counts),
                             Percentage = yr_percentages)
print(yr_summary)
```

```{r}
season_counts <- table(bikeDf$season) 
season_percentages <- prop.table(season_counts) * 100
season_summary <- data.frame(Season = names(season_counts),
                             Count = as.numeric(season_counts),
                             Percentage = season_percentages)
print(season_summary)
```

```{r}
holiday_counts <- table(bikeDf$holiday) 
holiday_percentages <- prop.table(holiday_counts) * 100
holiday_summary <- data.frame(holiday = names(holiday_counts),
                             Count = as.numeric(holiday_counts),
                             Percentage = holiday_percentages)
print(holiday_summary)
```

```{r}
workingday_counts <- table(bikeDf$workingday) 
workingday_percentages <- prop.table(workingday_counts) * 100
workingday_summary <- data.frame(workingday = names(workingday_counts),
                             Count = as.numeric(workingday_counts),
                             Percentage = workingday_percentages)
print(workingday_summary)
```

```{r}
weathersit_counts <- table(bikeDf$weathersit) 
weathersit_percentages <- prop.table(weathersit_counts) * 100
weathersit_summary <- data.frame(weathersit = names(weathersit_counts),
                             Count = as.numeric(weathersit_counts),
                             Percentage = weathersit_percentages)
print(weathersit_summary)
```


```{r}
#VIF for initial model
require(faraway)
model1 <- lm(cnt ~ ., data = bikeDf)
vif(model1)
```

```{r}
#VIF with atemp removed
model2 <- lm(cnt ~ yr + season + holiday + workingday + weathersit +temp + hum + windspeed, data = bikeDf)
vif(model2)
```


```{r}
#Density Plot: Bike Counts
library(ggplot2)
ggplot(bikeDf, aes(x = cnt)) +
  geom_density(color = "black") +
  labs(title = "",
       x = "Bike counts",
       y = "density") 

#Density Plot: Temperature
library(ggplot2)
ggplot(bikeDf, aes(x = temp)) +
  geom_density(color = "black") +
  labs(title = "",
       x = "Temperature",
       y = "density") 

#Density Plot: Weather
library(ggplot2)
ggplot(bikeDf, aes(x = weathersit)) +
  geom_density(color = "black") +
  labs(title = "",
       x = "Weather",
       y = "density") 
```

```{r}
#Boxplot for outliers
library(ggplot2)

box <- bikeDf[, c("temp", "windspeed", "hum")]
box <- stack(box)

ggplot(box, aes(x = ind, y = values)) +
  geom_boxplot(color = "black") +
  labs(title = "Box Plot of Temp, Windspeed, and Hum",
       x = "Variables",
       y = "Value") +
  theme_minimal()
```










